version: '24.0.6'

services:

    web:
      build:
        context: .
        dockerfile: Docker/nginx/Dockerfile
      ports:
        - "8088:80"
      volumes:
        - .:/app/
      links:
        - php

    php:
      build:
        context: .
        dockerfile: Docker/php/Dockerfile
      volumes:
          - .:/app/

    db:
      container_name: postgres_container
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: PAI
      ports:
        - "5432:5432"
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      volumes:
        - .:/app/
