version: '24.0.6'

services:

    web:
      build:
        context: .
        dockerfile: Docker/nginx/Dockerfile
      ports:
        - "8088:80"
      volumes:
        - .:/app/
      links:
        - php

    php:
      build:
        context: .
        dockerfile: Docker/php/Dockerfile
      volumes:
          - .:/app/

    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: Users
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - "5432:5432"
      volumes:
        - .:/app/
